image:
  file: .gitpod.Dockerfile
tasks:
- command: >
    ./build.sh --prefix /opt/darktable --build-type Release --install --sudo
vscode:
  extensions:
    - ms-vscode.cmake-tools
ports:
  - name: VNC
    description: VNC connect
    port: 6080
    onOpen: open-browser
