image:
  file: .gitpod.Dockerfile
tasks:
- command: >
    ./build.sh --prefix /opt/darktable --build-type Release --install --sudo
vscode:
  extensions:
    - ms-vscode.cpptools
    - ms-vscode.cpptools-extension-pack
    - ms-vscode.cmake-tools
